define(function () {
  'use strict';

  return {
    NEW_KEYFRAME_MS_INCREASE: 1000
    ,NEW_KEYFRAME_X_INCREASE: 100
    ,CUSTOM_CURVE_PREFIX: 'customCurve'
    ,HIDABLE_VIEW_TRANSITION_DURATION: 450
    ,CONTROL_PANEL_PADDING_FROM_CORNER: 30
  };
});
